"""Write every number the report quotes into report/numbers.tex as a macro.

The report then contains no hand-typed figures at all: if a run changes, the
numbers in the text change with it, and there is no way for the prose and the
data to drift apart.

    python scripts/report_numbers.py
"""

import argparse
import json
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from colorization.runs import list_runs, read_config  # noqa: E402


def fmt(x, places=2):
    return f"{x:.{places}f}"


def spread(values, places=2):
    """mean over seeds, with the min and max, since three runs is not a distribution."""
    if len(values) == 1:
        return fmt(values[0], places)
    return f"{fmt(statistics.mean(values), places)}~[{fmt(min(values), places)}, {fmt(max(values), places)}]"


def collect(results):
    runs = {"l2": [], "classification": []}
    for r in list_runs(results):
        runs[read_config(r)["loss"]].append(r)
    evals = {k: [json.loads((r / "eval.json").read_text()) for r in v] for k, v in runs.items()}
    return runs, evals


def at_temperature(ev, t):
    return min(ev["temperature_sweep"], key=lambda s: abs(s["temperature"] - t))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--out", default="report/numbers.tex")
    args = ap.parse_args()

    runs, evals = collect(args.results)
    base = json.loads((Path(args.results) / "baselines.json").read_text())
    mech = json.loads((Path(args.results) / "mechanism.json").read_text())
    cfg = read_config(runs["l2"][0])

    m = {}
    m["NSeeds"] = str(len(runs["l2"]))
    m["NEpochs"] = str(cfg["epochs"])
    m["BatchSize"] = str(cfg["batch_size"])
    m["BinSize"] = str(int(cfg["bin_size"]))
    m["NBins"] = str(evals["classification"][0]["n_bins"])
    m["NTest"] = f"{evals['l2'][0]['n_test']:,}".replace(",", "\\,")

    for name, ev in [("Grey", base["grey"]), ("Mean", base["training_mean"])]:
        m[f"Base{name}Err"] = fmt(ev["ab_error"])
        m[f"Base{name}Sat"] = fmt(100 * ev["saturation_ratio"], 1)
        m[f"Base{name}Spread"] = fmt(100 * ev["spread_ratio"], 1)

    m["LtwoErr"] = spread([e["test"]["ab_error"] for e in evals["l2"]])
    m["LtwoSat"] = spread([100 * e["test"]["saturation_ratio"] for e in evals["l2"]], 1)
    m["LtwoSpread"] = spread([100 * e["test"]["spread_ratio"] for e in evals["l2"]], 1)
    m["LtwoWithin"] = spread([100 * e["test"]["within_15"] for e in evals["l2"]], 1)

    # the best setting is whichever temperature minimises colour error, read off
    # the sweep rather than chosen by hand
    best_t = min(evals["classification"][0]["temperature_sweep"],
                 key=lambda s: s["ab_error"])["temperature"]
    for tag, t in [("Mode", 0.02), ("Best", best_t), ("Mean", 1.0)]:
        rows = [at_temperature(e, t) for e in evals["classification"]]
        m[f"Cls{tag}T"] = f"{rows[0]['temperature']:g}"
        m[f"Cls{tag}Err"] = spread([r["ab_error"] for r in rows])
        m[f"Cls{tag}Sat"] = spread([100 * r["saturation_ratio"] for r in rows], 1)
        m[f"Cls{tag}Spread"] = spread([100 * r["spread_ratio"] for r in rows], 1)

    same = [r for r in mech if r["same_seed"]]
    cross = [r for r in mech if not r["same_seed"]]
    m["MechSame"] = spread([r["l2_vs_expectation"]["mean_distance"] for r in same])
    m["MechCross"] = spread([r["l2_vs_expectation"]["mean_distance"] for r in cross])
    m["MechMode"] = spread([r["l2_vs_mode"]["mean_distance"] for r in mech])
    m["MechTruth"] = spread([r["l2_vs_truth"]["mean_distance"] for r in mech])
    m["MechCorr"] = fmt(statistics.mean(
        [r["l2_vs_expectation"]["corr_a"] for r in mech] +
        [r["l2_vs_expectation"]["corr_b"] for r in mech]), 3)
    pc = json.loads((Path(args.results) / "per_class.json").read_text())
    m["PerClassInstances"] = f"{pc['instances']:+.2f}"
    m["PerClassPixels"] = f"{pc['pixels']:+.2f}"

    m["MechRatio"] = fmt(
        statistics.mean([r["l2_vs_truth"]["mean_distance"] for r in mech]) /
        statistics.mean([r["l2_vs_expectation"]["mean_distance"] for r in mech]), 1)

    lines = ["% Generated by scripts/report_numbers.py. Do not edit by hand.",
             "% Every number quoted in the report is defined here and nowhere else."]
    for k, v in m.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")

    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"{len(m)} macros written to {args.out}")
    for k, v in m.items():
        print(f"  \\{k:16s} {v}")


if __name__ == "__main__":
    main()
